version: '3'
services:
  cloudant-developer:
    ports:
      - "7080:80"
    image: ibmcom/cloudant-developer:latest
    container_name: cloudant-developer
    volumes:
      - cloudant-developer:/srv
    build:
      context: .

  db2-developer:
    container_name: "db2-developer"
    build:
      context: .
    tty: true
    environment:
      - DB2INST1_PASSWORD=db2-dev-pw
      - LICENSE=accept
    ports:
      - "50000:50000"
    command: db2start

volumes:
  cloudant-developer:
